name: Build and Deploy

on:
  push:
  release:
    types: [published]

jobs:
  ci:
    if: github.run_number != 1 && github.ref_type != 'tag'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # extract `engines.node` from package.json and save it to output
      - name: Get Node.JS version from package.json
        id: get-versions
        run: echo node=$(jq -r '.engines.node // "lts/*"' ./package.json) >> $GITHUB_OUTPUT

      - name: Setup Node.JS
        uses: actions/setup-node@v3
        with:
          node-version: ${{steps.get-versions.outputs.node}}

      - name: Install dependencies
        run: npm install

      - name: Test
        run: npm run test

      - name: Build
        id: build
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        if: github.event_name == 'release' && env.NPM_TOKEN != null
        run: |
          npm run build
          tmp=$(mktemp)
          jq --arg version "${{ github.event.release.tag_name }}" '.version = $version' package.json > $tmp
          mv $tmp package.json
          echo version=$(jq -r '.version' package.json) >> $GITHUB_OUTPUT
      
      - name: Publish
        uses: JS-DevTools/npm-publish@v1
        if: steps.build.outputs.version != null
        with:
          token: ${{ secrets.NPM_TOKEN }}
