name: Setup Project

on:
  create

jobs:
  setup:
    if: github.run_number == 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Initialize
        run: |
          tmp=$(mktemp)
          jq --arg author "${{ github.repository_owner }}" '.author = $author' package.json > $tmp
          jq --arg url "${{ github.repositoryUrl }}" '.repository.url = "https+" + $url' $tmp > package.json
          jq --arg name "${{ github.event.repository.name }}" '.name = $name' package.json > $tmp
          mv $tmp package.json
          echo "# ${{ github.event.repository.name }}" > README.md
          rm -rf LICENSE

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Setup project"